version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    networks:
      - app-network

  app:
    image: php:8.3-fpm-alpine
    container_name: app
    restart: unless-stopped
    tty: true
    networks:
      - app-network
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/public
      - ./storage:/var/www/html/storage

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
